// Inicialización de variables
var tarjetasDestapadas = 0;
var tarjeta1 = null;
var tarjeta2 = null;
var primerResultado = null;
var segundoResultado = null;
var movimientos = 0;
var acierto = 0;
var temporizador = false;
var timer = 0;
var tiempo = null;
